In [1]:
import numpy as np

import model

In [2]:
arraySize = 10
sorter = model.StochasticSorter(arraySize)
for _ in range(100):
    test = np.random.randint(0, arraySize, arraySize)
    sorter.sort(test)

[[5 9 2 4 4 1 6 9 3 9]]
Prediction: [7 3]
[[5 9 2 9 4 1 6 4 3 9]]
Loss: 16.000187552271072
Prediction: [8 3]
[[5 9 2 3 4 1 6 4 9 9]]
Loss: -27.99981243936922
Prediction: [6 1]
[[5 6 2 3 4 1 9 4 9 9]]
Loss: -3.999812413350016
Prediction: [6 1]

[[8 4 4 9 9 2 9 3 1 1]]
Prediction: [6 3]
[[8 4 4 9 9 2 9 3 1 1]]
Loss: 0.00018758120766776664
Prediction: [6 3]

[[6 5 0 9 3 6 5 8 2 7]]
Prediction: [6 3]
[[6 5 0 5 3 6 9 8 2 7]]
Loss: -11.999812409261144
Prediction: [5 2]
[[6 5 6 5 3 0 9 8 2 7]]
Loss: 20.000187599500226
Prediction: [8 3]
[[6 5 6 2 3 0 9 8 5 7]]
Loss: -11.999812349097335
Prediction: [8 2]
[[6 5 5 2 3 0 9 8 6 7]]
Loss: -3.9998123364726483
Prediction: [8 1]
[[6 6 5 2 3 0 9 8 5 7]]
Loss: 8.000187657250775
Prediction: [8 2]
[[6 6 5 2 3 0 9 8 5 7]]
Loss: 0.00018765916470219303
Prediction: [8 2]

[[0 4 0 7 3 5 2 0 0 0]]
Prediction: [4 5]
[[0 4 0 7 5 3 2 0 0 0]]
Loss: 4.0001876574846476
Prediction: [5 5]
[[0 4 0 7 5 3 2 0 0 0]]
Loss: 0.00018765539147394636
Prediction: [5 5]

[[9 6 4 2 

[[1 4 1 7 9 5 1 3 3 7]]
Loss: -11.999812396044993
Prediction: [2 4]
[[1 4 9 7 1 5 1 3 3 7]]
Loss: 12.000187594241998
Prediction: [4 2]
[[1 4 1 7 9 5 1 3 3 7]]
Loss: -11.999812406196154
Prediction: [2 4]
[[1 4 9 7 1 5 1 3 3 7]]
Loss: 12.00018758545566
Prediction: [4 2]
[[1 4 1 7 9 5 1 3 3 7]]
Loss: -11.99981241451295
Prediction: [2 5]
[[1 4 5 7 9 1 1 3 3 7]]
Loss: 4.000187578173886
Prediction: [4 4]
[[1 4 5 7 9 1 1 3 3 7]]
Loss: 0.00018757927033216364
Prediction: [4 4]

[[6 5 6 9 2 0 6 0 7 0]]
Prediction: [5 1]
[[6 0 6 9 2 5 6 0 7 0]]
Loss: -11.999812420844089
Prediction: [3 1]
[[6 9 6 0 2 5 6 0 7 0]]
Loss: 12.000187580518569
Prediction: [1 0]
[[9 6 6 0 2 5 6 0 7 0]]
Loss: 4.0001875692040185
Prediction: [1 0]

[[9 5 1 9 2 1 4 2 2 5]]
Prediction: [4 1]
[[9 2 1 9 5 1 4 2 2 5]]
Loss: -3.999812433874674
Prediction: [4 1]

[[1 7 6 6 5 0 3 3 7 3]]
Prediction: [5 2]
[[1 7 0 6 5 6 3 3 7 3]]
Loss: -15.999812433659569
Prediction: [2 3]
[[1 7 6 0 5 6 3 3 7 3]]
Loss: 4.000187569692584
Prediction: [

Prediction: [6 3]
[[2 5 6 9 1 3 7 2 1 4]]
Loss: 4.000187483052294
Prediction: [6 3]

[[6 4 4 1 1 0 6 9 2 5]]
Prediction: [6 2]
[[6 4 6 1 1 0 4 9 2 5]]
Loss: 4.000187483934418
Prediction: [5 2]
[[6 4 0 1 1 6 4 9 2 5]]
Loss: -19.99981251707315
Prediction: [2 2]
[[6 4 0 1 1 6 4 9 2 5]]
Loss: 0.00018749017456198125
Prediction: [2 2]

[[3 3 2 4 6 3 8 0 3 2]]
Prediction: [4 3]
[[3 3 2 6 4 3 8 0 3 2]]
Loss: 4.000187490234411
Prediction: [4 3]

[[6 0 0 6 6 8 4 8 9 7]]
Prediction: [2 2]
[[6 0 0 6 6 8 4 8 9 7]]
Loss: 0.0001874919194484571
Prediction: [2 2]

[[0 7 9 4 9 0 7 0 0 2]]
Prediction: [4 4]
[[0 7 9 4 9 0 7 0 0 2]]
Loss: 0.00018749204807619465
Prediction: [4 4]

[[1 6 9 5 1 4 8 5 2 4]]
Prediction: [5 3]
[[1 6 9 4 1 5 8 5 2 4]]
Loss: -3.9998125077614057
Prediction: [5 3]

[[2 9 0 4 8 2 5 2 6 4]]
Prediction: [1 3]
[[2 4 0 9 8 2 5 2 6 4]]
Loss: -3.9998125067817893
Prediction: [4 4]
[[2 4 0 9 8 2 5 2 6 4]]
Loss: 0.00018749249606236188
Prediction: [4 4]

[[5 2 3 6 6 4 2 0 1 9]]
Prediction: [2 