In [1]:
import numpy as np

import Stochastic
import utils

In [40]:
arraySize = 10
old_train = np.random.randint(0, arraySize, arraySize)
print(old_train)
old_score = utils.score(old_train)
print(old_score)

[1 7 7 8 2 5 1 7 4 8]
12


In [41]:
sorter = Stochastic.Sorter(arraySize)

In [42]:
new_train = sorter.sort(old_train)
print(new_train.reshape(-1,).astype(int))
new_score = int(utils.score(new_train))
print(new_score)

[1 2 1 4 5 7 7 7 8 8]
76


In [43]:
print("{} -> {}, score diff {}"
      .format(old_train, new_train.reshape(-1,).astype(int), new_score - old_score))

[1 7 7 8 2 5 1 7 4 8] -> [1 2 1 4 5 7 7 7 8 8], score diff 64
